version: '3.8'

services:
  ludo-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - APPLICATION_SECRET=changeme-this-is-a-very-long-secret-key-that-should-be-changed
      - PLAY_HTTP_SECRET_KEY=changeme-this-is-a-very-long-secret-key-that-should-be-changed
    ports:
      - "9000:9000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s